# frozen_string_literal: true
# Copyright (C) 2024 mykaa. All rights reserved.

require "date"
require "fileutils"
require "json"
require "net/http"
require "set"
require "uri"
require "yaml"

module Jekyll
  module PluginSync
    class Engine
      PAGE_AUTOGEN_MARKER = "autogenerated: true"
      INCLUDE_AUTOGEN_HEADER = "<!-- AUTO-GENERATED by plugin_sync. Do not edit manually. -->\n\n"

      DEFAULT_CONFIG = {
        "enabled" => true,
        "github_user" => "mykaadev",
        "include_topics" => [],
        "include_repo_prefixes" => ["Ns"],
        "allow_prefix_fallback" => true,
        "include_repos" => [],
        "exclude_repos" => [],
        "include_archived" => false,
        "default_category" => "Utility",
        "default_thumbnail" => "/resources/images/plugins/UtilityAI.png",
        "generated_pages_dir" => "_generated/plugins",
        "generated_readmes_dir" => "_includes/generated/readmes",
        "readme_include_dir" => "generated/readmes",
        "download_footer" => true,
        "cleanup_when_empty" => false,
        "category_by_topic" => {
          "algorithm" => "Algorithm",
          "gameplay" => "Gameplay",
          "tools" => "Tools",
          "utility" => "Utility",
          "visuals" => "Visuals"
        },
        "repo_overrides" => {},
        "discussions" => {
          "enabled" => true,
          "category" => "General",
          "mapping" => "specific",
          "term_prefix" => "plugin-",
          "repo_overrides" => {}
        }
      }.freeze

      def initialize(site)
        @site = site
        @source = site.source
        @config = deep_merge(DEFAULT_CONFIG, stringify_keys(site.config["plugin_sync"] || {}))
        @github_user = @config["github_user"].to_s.strip
        @github_token = ENV["PLUGIN_SYNC_GITHUB_TOKEN"] || ENV["GITHUB_TOKEN"]
        @discussion_category_cache = {}
      end

      def sync!
        return unless truthy?(@config["enabled"])
        return if @github_user.empty?

        FileUtils.mkdir_p(readmes_dir)
        FileUtils.mkdir_p(pages_dir)

        repos = fetch_public_repositories
        if repos.empty?
          Jekyll.logger.warn("[plugin_sync] No repositories found for '#{@github_user}'. Keeping previous generated files.")
          return
        end

        generated_repo_names = []
        matched_candidates = 0

        repos.each do |repo|
          next unless repository_allowed?(repo)

          repo_name = repo["name"].to_s
          topics = fetch_repository_topics(repo_name)
          next unless plugin_repository?(repo_name, topics)

          matched_candidates += 1
          branch = repo["default_branch"].to_s.empty? ? "main" : repo["default_branch"].to_s
          readme_body = fetch_readme(repo_name, branch)
          if readme_body.nil? || readme_body.empty?
            Jekyll.logger.warn("[plugin_sync] README missing for #{repo_name}, skipping.")
            next
          end

          normalized_readme, readme_meta = normalize_readme(readme_body, repo_name, branch)
          page_data = build_page_data(repo, topics, readme_meta, branch)
          write_readme_include(repo_name, normalized_readme)
          write_plugin_page(repo_name, page_data)

          generated_repo_names << repo_name
          Jekyll.logger.info("[plugin_sync] Synced #{repo_name}")
        end

        if matched_candidates.zero?
          Jekyll.logger.warn("[plugin_sync] No repositories matched plugin filters. Keeping previous generated files.")
          return
        end

        if generated_repo_names.empty?
          Jekyll.logger.warn("[plugin_sync] No plugin pages were generated. Keeping previous generated files.")
          return
        end

        cleanup_stale_generated_files(generated_repo_names)
        Jekyll.logger.info("[plugin_sync] Generated #{generated_repo_names.size} plugin page(s).")
      end

      private

      def readmes_dir
        File.join(@source, @config["generated_readmes_dir"].to_s)
      end

      def pages_dir
        File.join(@source, @config["generated_pages_dir"].to_s)
      end

      def readme_include_dir
        @config["readme_include_dir"].to_s
      end

      def fetch_public_repositories
        results = []
        page = 1

        loop do
          url = "https://api.github.com/users/#{@github_user}/repos?type=public&sort=updated&per_page=100&page=#{page}"
          payload = github_get_json(url)
          break unless payload.is_a?(Array) && !payload.empty?

          results.concat(payload)
          break if payload.size < 100

          page += 1
        end

        results
      end

      def fetch_repository_topics(repo_name)
        payload = github_get_json("https://api.github.com/repos/#{@github_user}/#{repo_name}/topics")
        names = payload.is_a?(Hash) ? payload["names"] : []
        Array(names).map { |topic| topic.to_s.downcase }
      rescue StandardError => e
        Jekyll.logger.warn("[plugin_sync] Failed to fetch topics for #{repo_name}: #{e.message}")
        []
      end

      def repository_allowed?(repo)
        return false if repo.nil?

        repo_name = repo["name"].to_s
        return false if repo_name.empty?
        return false if Array(@config["exclude_repos"]).map(&:to_s).include?(repo_name)
        return false if repo["archived"] && !truthy?(@config["include_archived"])

        true
      end

      def plugin_repository?(repo_name, topics)
        include_repos = Array(@config["include_repos"]).map(&:to_s)
        return true if include_repos.include?(repo_name)

        include_topics = Array(@config["include_topics"]).map { |value| value.to_s.downcase }
        prefix_match = Array(@config["include_repo_prefixes"]).any? do |prefix|
          prefix_string = prefix.to_s
          !prefix_string.empty? && repo_name.start_with?(prefix_string)
        end

        topic_match = !(topics & include_topics).empty?
        return true if topic_match

        return true if include_topics.empty? && prefix_match
        return true if truthy?(@config["allow_prefix_fallback"]) && prefix_match

        false
      end

      def fetch_readme(repo_name, branch)
        url = URI("https://raw.githubusercontent.com/#{@github_user}/#{repo_name}/refs/heads/#{branch}/README.md")
        response = http_get(url)
        return nil unless response.is_a?(Net::HTTPSuccess)

        response.body.to_s.force_encoding("UTF-8")
      rescue StandardError => e
        Jekyll.logger.warn("[plugin_sync] Error fetching README for #{repo_name}: #{e.message}")
        nil
      end

      def normalize_readme(content, repo_name, branch)
        normalized = remove_gh_only_sections(content)
        normalized = strip_utf8_bom(normalized)
        normalized, extracted_meta = extract_meta_block(normalized)
        normalized = rewrite_asset_links(normalized, repo_name, branch)
        normalized = normalize_markdown_tables(normalized)

        if truthy?(@config["download_footer"])
          normalized = normalized.strip + "\n\n---\n\n> [Download on GitHub](https://github.com/#{@github_user}/#{repo_name})\n"
        end

        [normalized.strip + "\n", extracted_meta]
      end

      def strip_utf8_bom(content)
        content.to_s.sub(/\A\uFEFF/, "")
      end

      # Kramdown table parsing is strict and expects a blank line before table blocks.
      # Also normalize separator rows in case non-ASCII dashes sneak in from source markdown.
      def normalize_markdown_tables(content)
        lines = content.to_s.gsub("\r\n", "\n").split("\n", -1)
        lines.map! { |line| normalize_table_separator_line(line) }

        normalized = []
        lines.each_with_index do |line, idx|
          next_line = idx + 1 < lines.length ? lines[idx + 1] : nil
          if markdown_table_header_line?(line) && markdown_table_separator_line?(next_line)
            prev = normalized.last
            normalized << "" unless prev.nil? || prev.strip.empty?
          end
          normalized << line
        end

        normalized.join("\n")
      end

      def markdown_table_header_line?(line)
        stripped = line.to_s.strip
        return false if stripped.empty?
        return false unless stripped.start_with?("|") && stripped.end_with?("|")
        return false if markdown_table_separator_line?(stripped)

        true
      end

      def markdown_table_separator_line?(line)
        stripped = line.to_s.strip
        return false if stripped.empty?
        return false unless stripped.match?(/\A\|?[\s:\-\u2013\u2014|]+\|?\z/)

        inner = stripped.sub(/\A\|/, "").sub(/\|\z/, "")
        cells = inner.split("|").map(&:strip)
        return false if cells.length < 2

        cells.all? { |cell| cell.match?(/\A:?[ \-\u2013\u2014]{1,}:?\z/) }
      end

      def normalize_table_separator_line(line)
        return line unless markdown_table_separator_line?(line)

        indent = line[/^\s*/].to_s
        stripped = line.strip
        has_leading_pipe = stripped.start_with?("|")
        has_trailing_pipe = stripped.end_with?("|")
        inner = stripped.sub(/\A\|/, "").sub(/\|\z/, "")

        rebuilt_cells = inner.split("|").map do |cell|
          token = cell.strip
          next token unless token.match?(/\A:?[ \-\u2013\u2014]{1,}:?\z/)

          left = token.start_with?(":") ? ":" : ""
          right = token.end_with?(":") ? ":" : ""
          "#{left}---#{right}"
        end

        rebuilt = rebuilt_cells.join("|")
        rebuilt = "|#{rebuilt}" if has_leading_pipe
        rebuilt = "#{rebuilt}|" if has_trailing_pipe

        "#{indent}#{rebuilt}"
      end
      def remove_gh_only_sections(content)
        content.gsub(/<!--\s*GH_ONLY_START\s*-->.*?<!--\s*GH_ONLY_END\s*-->/m, "")
      end

      def extract_meta_block(content)
        metadata = {}
        cleaned = content.gsub(/<!--\s*PLUGIN_META(.*?)PLUGIN_META\s*-->/m) do
          raw_meta = Regexp.last_match(1).to_s.strip
          begin
            parsed = YAML.safe_load(raw_meta)
            if parsed.is_a?(Hash)
              metadata.merge!(stringify_keys(parsed))
            end
          rescue StandardError => e
            Jekyll.logger.warn("[plugin_sync] Could not parse PLUGIN_META block: #{e.message}")
          end
          ""
        end

        [cleaned, metadata]
      end

      def rewrite_asset_links(content, repo_name, branch)
        raw_base = "https://raw.githubusercontent.com/#{@github_user}/#{repo_name}/refs/heads/#{branch}/"

        rewritten = content.gsub(/!\[([^\]]*)\]\(([^)]+)\)/) do
          alt_text = Regexp.last_match(1)
          link = Regexp.last_match(2)
          "![#{alt_text}](#{absolutize_media_url(link, raw_base, repo_name, branch)})"
        end

        rewritten.gsub(/(<(?:img|video|source)\b[^>]*?\s(?:src|poster)=["'])([^"']+)(["'])/i) do
          prefix = Regexp.last_match(1)
          link = Regexp.last_match(2)
          suffix = Regexp.last_match(3)
          "#{prefix}#{absolutize_media_url(link, raw_base, repo_name, branch)}#{suffix}"
        end
      end

      def absolutize_media_url(link, raw_base, repo_name, branch)
        original = link.to_s.strip
        return original if original.empty?
        return original if original.start_with?("#")
        return original if original.match?(/\A(?:mailto|data|javascript):/i)

        blob_to_raw = github_blob_to_raw(original, raw_base, repo_name, branch)
        return blob_to_raw unless blob_to_raw.nil?

        return original if original.match?(/\Ahttps?:\/\//i)

        path = original.sub(/\A\.\//, "")
        path = path.sub(%r{\A/}, "")
        URI.join(raw_base, path).to_s
      rescue StandardError
        original
      end

      def github_blob_to_raw(url, raw_base, repo_name, branch)
        uri = URI.parse(url)
        return nil unless uri.host == "github.com"

        parts = uri.path.split("/")
        return nil if parts.size < 6
        return nil unless parts[1] == @github_user && parts[2] == repo_name
        return nil unless parts[3] == "blob" && parts[4] == branch

        blob_path = parts[5..].join("/")
        URI.join(raw_base, blob_path).to_s
      rescue StandardError
        nil
      end

      def build_page_data(repo, topics, meta, branch)
        repo_name = repo["name"].to_s
        overrides = stringify_keys((@config["repo_overrides"] || {})[repo_name] || {})

        short_description = first_present(
          overrides["short-description"],
          overrides["short_description"],
          meta["short-description"],
          meta["short_description"],
          repo["description"],
          "Unreal Engine plugin"
        )

        title_value = first_present(overrides["title"], meta["title"], humanize_repo_name(repo_name))
        description_value = first_present(overrides["description"], meta["description"], short_description)
        category_value = first_present(
          overrides["category"],
          meta["category"],
          category_from_topics(topics),
          @config["default_category"]
        )
        thumbnail_value = first_present(
          overrides["thumbnail"],
          meta["thumbnail"],
          "https://raw.githubusercontent.com/#{@github_user}/#{repo_name}/refs/heads/#{branch}/Resources/Banner.png",
          @config["default_thumbnail"]
        )

        permalink_value = first_present(
          overrides["permalink"],
          meta["permalink"],
          "/plugins/#{slugify(repo_name)}/"
        )

        discussion_data = build_discussion_data(repo_name, repo, overrides, meta)
        date_value = parse_date(first_present(overrides["date"], meta["date"], repo["pushed_at"], repo["created_at"]))
        {
          "title" => title_value,
          "short-description" => short_description,
          "description" => description_value,
          "category" => category_value,
          "thumbnail" => thumbnail_value,
          "date" => date_value.strftime("%Y-%m-%d"),
          "topics" => topics,
          "github" => repo["html_url"].to_s.empty? ? "https://github.com/#{@github_user}/#{repo_name}" : repo["html_url"].to_s,
          "permalink" => permalink_value,
          "discussion" => discussion_data["enabled"],
          "discussion_mapping" => discussion_data["mapping"],
          "discussion_term" => discussion_data["term"],
          "discussion_repo" => discussion_data["repo"],
          "discussion_repo_id" => discussion_data["repo_id"],
          "discussion_category" => discussion_data["category"],
          "discussion_category_id" => discussion_data["category_id"],
          "discussion_configured" => discussion_data["configured"]
        }
      end

      def write_readme_include(repo_name, readme_content)
        path = File.join(readmes_dir, "#{repo_name}.md")
        File.write(path, INCLUDE_AUTOGEN_HEADER + readme_content)
      end

      def write_plugin_page(repo_name, page_data)
        path = File.join(pages_dir, "#{repo_name}.md")
        topics = Array(page_data["topics"]).map { |topic| "  - \"#{escape_yaml(topic)}\"" }.join("\n")

        page_content = <<~MARKDOWN
          ---
          layout: plugin
          autogenerated: true
          nav: plugins
          title: "#{escape_yaml(page_data["title"])}"
          short-description: "#{escape_yaml(page_data["short-description"])}"
          description: "#{escape_yaml(page_data["description"])}"
          thumbnail: "#{escape_yaml(page_data["thumbnail"])}"
          date: #{page_data["date"]}
          category: "#{escape_yaml(page_data["category"])}"
          repo: "#{escape_yaml(repo_name)}"
          github: "#{escape_yaml(page_data["github"])}"
          permalink: "#{escape_yaml(page_data["permalink"])}"
          discussion: #{page_data["discussion"] ? "true" : "false"}
          discussion_heading: "Discuss this plugin"
          discussion_description: "Comment here and this thread lives in the plugin repository discussions."
          discussion_mapping: "#{escape_yaml(page_data["discussion_mapping"])}"
          discussion_term: "#{escape_yaml(page_data["discussion_term"])}"
          discussion_repo: "#{escape_yaml(page_data["discussion_repo"])}"
          discussion_repo_id: "#{escape_yaml(page_data["discussion_repo_id"])}"
          discussion_category: "#{escape_yaml(page_data["discussion_category"])}"
          discussion_category_id: "#{escape_yaml(page_data["discussion_category_id"])}"
          discussion_configured: #{page_data["discussion_configured"] ? "true" : "false"}
          topics:
          #{topics.empty? ? "  - plugin" : topics}
          ---

          {% include #{readme_include_dir}/#{repo_name}.md %}
        MARKDOWN

        File.write(path, page_content)
      end

      def build_discussion_data(repo_name, repo, overrides, meta)
        discussions_cfg = stringify_keys(@config["discussions"] || {})
        enabled = truthy?(discussions_cfg.fetch("enabled", true))

        mapping_value = first_present(
          overrides["discussion-mapping"],
          overrides["discussion_mapping"],
          meta["discussion-mapping"],
          meta["discussion_mapping"],
          discussions_cfg["mapping"],
          "specific"
        )

        term_prefix = first_present(discussions_cfg["term_prefix"], "plugin-")
        term_value = first_present(
          overrides["discussion-term"],
          overrides["discussion_term"],
          meta["discussion-term"],
          meta["discussion_term"],
          "#{term_prefix}#{slugify(repo_name)}"
        )

        discussion_repo_value = first_present(
          overrides["discussion-repo"],
          overrides["discussion_repo"],
          meta["discussion-repo"],
          meta["discussion_repo"],
          "#{@github_user}/#{repo_name}"
        )

        discussion_repo_id_value = first_present(
          overrides["discussion-repo-id"],
          overrides["discussion_repo_id"],
          meta["discussion-repo-id"],
          meta["discussion_repo_id"],
          repo["node_id"]
        )

        category_value = first_present(
          overrides["discussion-category"],
          overrides["discussion_category"],
          meta["discussion-category"],
          meta["discussion_category"],
          discussion_repo_override(repo_name, discussions_cfg, "category"),
          discussions_cfg["category"],
          "General"
        )

        category_id_value = first_present(
          overrides["discussion-category-id"],
          overrides["discussion_category_id"],
          meta["discussion-category-id"],
          meta["discussion_category_id"],
          discussion_repo_override(repo_name, discussions_cfg, "category_id")
        )

        if category_id_value.empty? && enabled
          resolved_category = fetch_discussion_category(repo_name, category_value)
          unless resolved_category.nil?
            category_value = first_present(category_value, resolved_category["name"])
            category_id_value = first_present(category_id_value, resolved_category["id"])
          end
        end

        configured = enabled &&
                     !discussion_repo_value.empty? &&
                     !discussion_repo_id_value.empty? &&
                     !category_value.empty? &&
                     !category_id_value.empty?

        if enabled && !configured
          Jekyll.logger.warn("[plugin_sync] Discussion setup incomplete for #{repo_name}; skipping embedded discussion.")
        end

        {
          "enabled" => enabled,
          "mapping" => mapping_value,
          "term" => term_value,
          "repo" => discussion_repo_value,
          "repo_id" => discussion_repo_id_value,
          "category" => category_value,
          "category_id" => category_id_value,
          "configured" => configured
        }
      end

      def discussion_repo_override(repo_name, discussions_cfg, key)
        repo_overrides = stringify_keys(discussions_cfg["repo_overrides"] || {})
        repo_cfg = stringify_keys(repo_overrides[repo_name] || {})
        first_present(repo_cfg[key])
      end

      def fetch_discussion_category(repo_name, preferred_category)
        cache_key = "#{repo_name}:#{preferred_category.to_s.downcase}"
        return @discussion_category_cache[cache_key] if @discussion_category_cache.key?(cache_key)

        payload = github_get_json("https://api.github.com/repos/#{@github_user}/#{repo_name}/discussions/categories")
        categories = payload.is_a?(Array) ? payload : []
        if categories.empty?
          @discussion_category_cache[cache_key] = nil
          return nil
        end

        preferred = preferred_category.to_s.strip.downcase
        selected = categories.find { |category| category["name"].to_s.strip.downcase == preferred }
        selected ||= categories.first

        result = {
          "id" => selected["node_id"].to_s,
          "name" => selected["name"].to_s
        }

        @discussion_category_cache[cache_key] = result
      rescue StandardError => e
        Jekyll.logger.warn("[plugin_sync] Could not fetch discussion categories for #{repo_name}: #{e.message}")
        @discussion_category_cache[cache_key] = nil
      end

      def cleanup_stale_generated_files(current_repo_names)
        current_set = current_repo_names.map(&:to_s).to_set
        return if current_set.empty? && !truthy?(@config["cleanup_when_empty"])

        Dir.glob(File.join(pages_dir, "*.md")).each do |path|
          file_content = File.read(path)
          next unless file_content.include?(PAGE_AUTOGEN_MARKER)

          repo_name = File.basename(path, ".md")
          next if current_set.include?(repo_name)

          FileUtils.rm_f(path)
          Jekyll.logger.info("[plugin_sync] Removed stale page #{repo_name}.md")
        end

        Dir.glob(File.join(readmes_dir, "*.md")).each do |path|
          file_content = File.read(path)
          next unless file_content.start_with?(INCLUDE_AUTOGEN_HEADER.strip)

          repo_name = File.basename(path, ".md")
          next if current_set.include?(repo_name)

          FileUtils.rm_f(path)
          Jekyll.logger.info("[plugin_sync] Removed stale README include #{repo_name}.md")
        end

        cleanup_legacy_generated_files(current_set)
      end

      def cleanup_legacy_generated_files(_current_set)
        legacy_pages_dir = File.join(@source, "plugins")
        legacy_readmes_dir = File.join(@source, "_includes", "readmes")

        if legacy_pages_dir != pages_dir
          Dir.glob(File.join(legacy_pages_dir, "*.md")).each do |path|
            file_content = File.read(path)
            next unless file_content.include?(PAGE_AUTOGEN_MARKER)

            repo_name = File.basename(path, ".md")
            FileUtils.rm_f(path)
            Jekyll.logger.info("[plugin_sync] Removed legacy autogenerated page #{repo_name}.md")
          end
        end

        if legacy_readmes_dir != readmes_dir
          Dir.glob(File.join(legacy_readmes_dir, "*.md")).each do |path|
            file_content = File.read(path)
            next unless file_content.start_with?(INCLUDE_AUTOGEN_HEADER.strip)

            repo_name = File.basename(path, ".md")
            FileUtils.rm_f(path)
            Jekyll.logger.info("[plugin_sync] Removed legacy autogenerated README #{repo_name}.md")
          end
        end
      end

      def category_from_topics(topics)
        map = stringify_keys(@config["category_by_topic"] || {})
        topics.each do |topic|
          mapped = map[topic.to_s.downcase]
          return mapped unless mapped.to_s.strip.empty?
        end
        nil
      end

      def parse_date(value)
        return Date.today if value.nil?
        return value.to_date if value.respond_to?(:to_date)

        Date.parse(value.to_s)
      rescue StandardError
        Date.today
      end

      def humanize_repo_name(repo_name)
        trimmed = repo_name.to_s.sub(/\ANs/, "")
        words = trimmed.gsub(/([a-z0-9])([A-Z])/, "\\1 \\2")
        words.strip.empty? ? repo_name.to_s : words
      end

      def slugify(value)
        value.to_s
          .downcase
          .gsub(/[^a-z0-9]+/, "-")
          .gsub(/\A-+|-+\z/, "")
      end

      def first_present(*values)
        values.find { |value| !value.to_s.strip.empty? }.to_s
      end

      def escape_yaml(value)
        value.to_s.gsub("\\", "\\\\").gsub("\"", "\\\"")
      end

      def truthy?(value)
        [true, "true", 1, "1", "yes", "on"].include?(value)
      end

      def stringify_keys(object)
        case object
        when Hash
          object.each_with_object({}) do |(key, value), acc|
            acc[key.to_s] = stringify_keys(value)
          end
        when Array
          object.map { |item| stringify_keys(item) }
        else
          object
        end
      end

      def deep_merge(base, override)
        merged = base.dup
        override.each do |key, value|
          if merged[key].is_a?(Hash) && value.is_a?(Hash)
            merged[key] = deep_merge(merged[key], value)
          else
            merged[key] = value
          end
        end
        merged
      end

      def github_get_json(url)
        response = http_get(URI(url))
        return nil unless response.is_a?(Net::HTTPSuccess)

        JSON.parse(response.body)
      rescue StandardError => e
        Jekyll.logger.warn("[plugin_sync] GitHub request failed (#{url}): #{e.message}")
        nil
      end

      def http_get(uri)
        request = Net::HTTP::Get.new(uri)
        request["Accept"] = "application/vnd.github+json"
        request["User-Agent"] = "mykaadev-portfolio-plugin-sync"
        request["X-GitHub-Api-Version"] = "2022-11-28"
        request["Authorization"] = "Bearer #{@github_token}" unless @github_token.to_s.strip.empty?

        Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https") do |http|
          http.request(request)
        end
      end
    end
  end
end

Jekyll::Hooks.register :site, :after_reset do |site|
  Jekyll::PluginSync::Engine.new(site).sync!
end
